//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaClases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        public string Numero { get; set; }
        public System.DateTime Creacion { get; set; }
        public string Termino { get; set; }
        public string RutCliente { get; set; }
        public string TipoEvento { get; set; }
        public string ModalidadServicio { get; set; }
        public double Asistentes { get; set; }
        public double ValorBase { get; set; }
        public double PersonalAdicional { get; set; }
        public string EstadoContrato { get; set; }
        public double ValorTotalContrato { get; set; }
        public string Observaciones { get; set; }
    }
}
